### ISSUE TITLE
Update to 1.15.1

### ISSUE THREAD

**Issue by itan1** [jw3126/ONNXRunTimeArtifacts#1]
Hi, I would like to use ONNXRunTime.jl in a project, preferably compatible with ONNXRuntime 1.15.1 because some operators changed (Softmax in my case).

I updated `version` to 1.15.1 in script.jl and tried to run it, but this gives me the following error:

`ERROR: LoadError: RequestError: HTTP/2 404 while requesting https://github.com/jw3126/ONNXRunTimeArtifacts/releases/download/v1.15.1-rc2/onnxruntime-win-x64-1.15.1.tgz`

I guess because this file does not exist yet.

Is there anything I should do before running the script? Thanks!

**Comment by itan1** [comment]
Ok I think I got it, sorry I haven't used artifacts a lot yet.

If I understood correctly now I have to

1. Wait for the merge into main
2. Create a release tag v1.15.1
3. Repackage the windows .zip binaries to .tgz and add them to the release tag in this repository

**Comment by jw3126** [comment]
Yes, that is correct, I will take care of this.

**Comment by itan1** [comment]
Amazing thank you for the super quick updates!

**Comment by jw3126** [comment]
released https://github.com/JuliaRegistries/General/pull/88787#event-9976362519
